name: C/C++ CI

on:
  push:
    branches: [ work ]
  pull_request:
    branches: [ work ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: format
      run: |
        sudo apt install clang-format
        clang-format -i **/*.h **/*.c
    - name: make
      run: make
